force-app/main/default/objects/Developer__c/Developer__c.object-meta.xml
<CustomObject>
    <label>Developer</label>
    <nameField>
        <label>Developer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Developers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Developer__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <label>Organization</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/InsertionMirketa.cls
public with sharing class InsertionMirketa {
    public static void InsertionMirketaHandler(List<Developer__c> l1) {
        List<String> devList = new List<String>();
        devList.add('Developer__c');

        
        List<Schema.DescribeSObjectResult> developerObjResult = Schema.describeSObjects(devList);
        Map<String, Schema.SObjectField> fieldMap = developerObjResult[0].fields.getMap();
        if (fieldMap.containsKey('Organization__c')) {
            for (Developer__c dev : l1) {
                dev.Organization__c = 'Mirketa'; 	
            } 
        }



    }
}